# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to EC2
        run: |
          scp -r ./build <ec2_user>@<ec2_instance_ip>:<ec2_destination_path>
          ssh <ec2_user>@<ec2_instance_ip> 'sudo cp -r <ec2_destination_path>/build/* /var/www/html'
